{% set name = "gcloud-aio-auth" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_auth-{{ version }}.tar.gz
  sha256: d37db2e6b6ce332812fd7ca41334fa2a2fe8238fd615c0765434e19c9d9239bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - aiohttp >=3.3.0,<4.0.0
    - backoff >=1.0.0,<3.0.0
    - chardet >=2.0,<6.0
    - cryptography >=2.0.0,<41.0.0
    - pyjwt >=1.5.3,<3.0.0
    - setuptools >=66.0.0,<67.0.0

test:
  imports:
    - gcloud.aio.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Auth
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
