{% set name = "gcloud-aio-auth" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_auth-{{ version }}.tar.gz
  sha256: 9ff6cb403b464b8941fbdd787da3fa0d99560ef2b3f35ffd242d50e1e5139eaa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - aiohttp >=3.3.0,<3.9.2
    - backoff >=1.0.0,<3.0.0
    - chardet >=2.0,<6.0
    - cryptography >=2.0.0,<45.0.0
    - pyjwt >=1.5.3,<3.0.0

test:
  imports:
    - gcloud.aio.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Auth
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
