{% set name = "gcloud-aio-auth" %}
{% set version = "4.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d96dc709e1eb6ee3f5b95ce70b59461d34ef24e48616bc56abf4b3a69b2385b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - aiohttp >=3.3.0,<4.0.0
    - backoff >=1.0.0,<3.0.0
    - chardet >=2.0,<4.1
    - cryptography >=2.0.0,<40.0.0
    - future >=0.17.0,<0.19.0
    - pyjwt >=1.5.3,<3.0.0
    - setuptools >=66.0.0,<67.0.0
    - six >=1.11.0,<2.0.0

test:
  imports:
    - gcloud.aio.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Auth
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
