{% set name = "gcloud-aio-auth" %}
{% set version = "5.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_auth-{{ version }}.tar.gz
  sha256: d4bd7c65e6db7908d3cbb1e1b3a394c6afa5526c6be0bf8600b33f8665d45b40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - aiohttp >=3.9.0,<4.0.0
    - backoff >=1.0.0,<3.0.0
    - chardet >=2.0,<6.0
    - cryptography >=2.0.0,<45.0.0
    - pyjwt >=1.5.3,<3.0.0

test:
  imports:
    - gcloud.aio.auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Auth
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
